### ISSUE TITLE
CookieJar store is not synchronous; use async API instead.

### ISSUE THREAD

**Issue by mohilles** [benkroeger/redis-cookie-store#6] opened 2019-08-04 18:26 UTC
Hi,
i tried to save cookieJar to redis 
```javascript
const RedisCookieStore = require('redis-cookie-store');
const redis = require('redis');
const request = require('request-promise');

const client = redis.createClient(process.env.REDIS_URL);
const jar = request.jar(new RedisCookieStore(client, 'google'));

const google = request({ url: 'https://www.google.com', jar, method: 'get' });
google
  .then(() => {
    console.log(jar);
  })
  .catch((e) => {
    console.log(e);
  });

```

have errors: 
```
throw new Error('CookieJar store is not synchronous; use async API instead.');
^
Error: CookieJar store is not synchronous; use async API instead.
```

please help!

**Comment by benkroeger** [comment] 2019-08-05 12:37
the error message basically tells you everything. the `request` library doesn't support async `CookieJarStorage`'s (which is implied if you want to store cookies anywhere else but in memory).

I've written my own wrapper around `request` to support plugins that perform async actions before and / or after any request / response: [oniyi-http-client](https://www.npmjs.com/package/oniyi-http-client). It also comes with a [plugin implementation for handling async cookie jar storages](https://github.com/benkroeger/oniyi-http-client/blob/master/plugins/async-cookie-jar.js)

**Comment by mohilles** [comment] 2019-08-05 14:03
After using **oniyi-http-client** with redis storing: 

```javascript 

const httpClient = require('oniyi-http-client');

const redis = require('redis');
const RedisStore = require('redis-cookie-store');

const client = redis.createClient(process.env.REDIS_URL);
const store = new RedisStore(client, 'userid');
const jar = httpClient.jar(store);

httpClient.get('URL_TO_GET_COOKIE', { jar }, (err, response, body) => {
  if (err) {
    // handle error here
  }
  console.log(jar);
  console.log(body);
  // do something with response and / or body
  const jar2 = httpClient.jar(store);
  httpClient.post('URL_TO_READ_COOKIE', { jar2 }, (err, response, body) => {
    if (err) {
      // handle error here
    }
    console.log(jar2);
    console.log(body);
    // do something with response and / or body
  });
});
```

i have this error msg:
```
(node:86072) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'secure' of undefined
    at CookieJar.getCookies (/project/node_modules/oniyi-http-client/node_modules/tough-cookie/lib/cookie.js:1122:24)
    at CookieJar.getCookieString (/project/node_modules/oniyi-http-client/node_modules/tough-cookie/lib/cookie.js:1223:19)
    at Request.jar (/project/node_modules/request/request.js:1455:33)
    at Request.init (/project/node_modules/request/request.js:301:8)
    at new Request (/project/node_modules/request/request.js:127:8)
    at requestPhaseList.run (/project/node_modules/oniyi-http-client/lib/make-request.js:120:13)
    at /project/node_modules/async/dist/async.js:473:16
    at replenish (/project/node_modules/async/dist/async.js:1006:25)
    at /project/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/project/node_modules/async/dist/async.js:3196:24)
(node:86072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:86072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by benkroeger** [comment] 2019-08-05 15:29
a couple of things wrong here:
- plugin isn't mounted
- two different jars with the same Redis client
- the second request receives jar with the wrong name in options (`jar2` instead of `jar`)

I didn't run the following code... but it should have all the relevant pieces

```js
const httpClient = require('oniyi-http-client');
const asyncCookieJarPlugin = require('oniyi-http-client/plugins/async-cookie-jar');

const redis = require('redis');
const RedisStore = require('redis-cookie-store');

const client = redis.createClient(process.env.REDIS_URL);
const store = new RedisStore(client, 'userid');
const jar = httpClient.jar(store);

httpClient.use(asyncCookieJarPlugin);

httpClient.get('URL_TO_GET_COOKIE', { jar }, (err, response, body) => {
  if (err) {
    // handle error here
  }
  console.log(jar);
  console.log(body);
  // do something with response and / or body
  httpClient.post('URL_TO_READ_COOKIE', { jar }, (err, response, body) => {
    if (err) {
      // handle error here
    }
    console.log(jar);
    console.log(body);
    // do something with response and / or body
  });
});
```


Also, I recommend creating your own httpClient instance (with `.create()` instead of mounting plugins into the default instance. This makes things easier if you need different plugins or plugin configurations throughout code in the same node process.

**Comment by benkroeger** [comment] 2019-08-05 15:30
also see [using plugins](https://github.com/benkroeger/oniyi-http-client#using-plugins) and [`httpClient.use()`](https://github.com/benkroeger/oniyi-http-client#HttpClient+use)

**Comment by mohilles** [comment] 2019-08-05 19:39
Thank you very much, for helping with this issue. I will try this code. 

My goal is create app, that save client cookie from requests, to use it with differences further requests not as the same time of the first request and even after restating the server. I think it’s possible.

**Comment by mohilles** [comment] 2019-08-05 22:45
the following code running without errors, but still not saving the cookies:
```javascript 
const redis = require('redis');
const RedisStore = require('redis-cookie-store');
const httpClient = require('oniyi-http-client');
const asyncCookieJarPlugin = require('oniyi-http-client/plugins/async-cookie-jar');

const client = redis.createClient();

const store = new RedisStore(client);

const customHttp = httpClient.create({});
const jar = customHttp.jar(store);

customHttp.use(asyncCookieJarPlugin);

customHttp.get('http://httpbin.org/cookies/set/ping/pong', { jar }, (err, response, body) => {
  if (err) return console.log(error);
  console.log(jar);
  return customHttp.get('http://httpbin.org/cookies', { jar }, (err, response, body) => {
    if (err) return console.log(error);
    console.log(jar);
  });
});
```

result: 

```
{
  "cookies": {}
}

{
  "cookies": {}
}
```

**Comment by mohilles** [comment] 2019-08-05 23:09
Please can you test redis-cookie-store Library, its successfully (for domains like google.com ..., not for domains like httpbin.org ! dont know why ) store to redis, but its not restoring any data to reuse. 

Thank you

**Comment by benkroeger** [comment] 2019-08-06 08:49
First: the contents of an async cookie jar can not be simply looged to console (they don't exist in memory and thus would always be empty).

Secondly, the issue isn't within this repository / module. It appears that the async-cookie-jar plugin uses `uri.href` to resolve cookies from the jar. As long as you provide the url as string, this prop is undefined and no cookies are loaded from the jar.
I've now updated that plugin in [`oniyi-http-client:2.0.6`](https://github.com/benkroeger/oniyi-http-client/commit/17816dc419774e28921dbbb90272d62b6307011d).
You should update to `oniyi-http-client:2.0.6`. I've tested with the following code:

```js
const redis = require("redis");
const RedisStore = require("redis-cookie-store");
const httpClient = require("oniyi-http-client");
const asyncCookieJarPlugin = require("oniyi-http-client/plugins/async-cookie-jar");

const client = redis.createClient();

const store = new RedisStore(client);

const customHttp = httpClient.create({});
const jar = customHttp.jar(store);

customHttp.use(asyncCookieJarPlugin);

customHttp.get(
  "http://httpbin.org/cookies/set/ping/pong",
  { jar, followRedirect: false },
  (err, response, body) => {
    if (err) return console.log(error);
    console.log("received set-cookie headers", response.headers["set-cookie"]);

    return customHttp.get(
      "http://httpbin.org/cookies",
      { jar },
      (err, response, body) => {
        if (err) return console.log(error);
        console.log("sent cookies to test server", response.request.headers);
        console.log('received response from test server', { body });
        jar;
      }
    );
  }
);
```

results:

```
received set-cookie headers [ 'ping=pong; Path=/' ]
sent cookies to test server { cookie: 'ping=pong; ' }
received response from test server { body: '{\n  "cookies": {\n    "ping": "pong"\n  }\n}\n' }
```

Closing this issue since your challenges are not related to `redis-cookie-store`.

**Closed by benkroeger** 2019-08-06 08:49 UTC
Labels: question
